basePath: /api/v1
definitions:
  utils.ResponseData:
    properties:
      code:
        type: integer
      href:
        type: string
      message:
        type: string
    type: object
  utils.ResponseMessage:
    properties:
      data:
        type: object
      errors:
        items:
          $ref: '#/definitions/utils.ResponseData'
        type: array
      messages:
        items:
          $ref: '#/definitions/utils.ResponseData'
        type: array
    type: object
  validators.CreateBody:
    properties:
      insUserId:
        type: integer
      name:
        type: string
    type: object
  validators.UpdateBody:
    properties:
      name:
        type: string
      setUserId:
        type: integer
    type: object
host: localhost:3030
info:
  contact:
    email: brian.campos.castro@gmail.com
    name: Brian Campos Castro
  description: Games Provider API is a 4G Solution. Responsible of managing information emails..
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: 4g Emailing API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: returns the time from DB
      parameters:
      - description: API_KEY Header
        in: header
        name: API_KEY
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: returns the time from DB
      models:
      - commons
  /models:
    get:
      consumes:
      - application/json
      description: Get all the models by defining the fields
      parameters:
      - description: API_KEY Header
        in: header
        name: API_KEY
        required: true
        type: string
      - description: Event fields
        in: query
        items:
          type: string
        name: fields
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: Get all models
      models:
      - models
    post:
      consumes:
      - application/json
      description: Create a new model item
      parameters:
      - description: New model
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/validators.CreateBody'
      - description: API_KEY Header
        in: header
        name: API_KEY
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: Create a model
      models:
      - models
  /models/{id}:
    get:
      consumes:
      - application/json
      description: Get a model by id
      parameters:
      - description: API_KEY Header
        in: header
        name: API_KEY
        required: true
        type: string
      - description: model ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: Get a model
      models:
      - models
    put:
      consumes:
      - application/json
      description: Update a model item
      parameters:
      - description: API_KEY Header
        in: header
        name: API_KEY
        required: true
        type: string
      - description: model ID
        in: path
        name: id
        required: true
        type: string
      - description: model Updated
        in: body
        name: model
        required: true
        schema:
          $ref: '#/definitions/validators.UpdateBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: Update a model
      models:
      - models
  /models/list:
    get:
      consumes:
      - application/json
      description: Get all the models by ids
      parameters:
      - description: API_KEY Header
        in: header
        name: API_KEY
        required: true
        type: string
      - description: models IDs
        in: query
        items:
          type: string
        name: modelIds
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.ResponseMessage'
      summary: Get all models by ids
      models:
      - models
swagger: "2.0"
